services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: vkr_pgvector_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: reestr_pro_db
    ports:
      - "5433:5432"
    volumes:
      - pgvector_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d reestr_pro_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgvector_data:
