"""first migration

Revision ID: fb1563c51059
Revises: 
Create Date: 2026-05-07 18:34:56.339746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fb1563c51059'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=False),
    sa.Column('source_file_name', sa.String(length=255), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('processed_rows', sa.Integer(), nullable=False),
    sa.Column('failed_rows', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_batches_id'), 'import_batches', ['id'], unique=False)
    op.create_table('registry_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_batch_id', sa.Integer(), nullable=False),
    sa.Column('source_document_id', sa.String(length=255), nullable=True),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('document_number', sa.String(length=255), nullable=False),
    sa.Column('temporary_number', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('registered_at', sa.Date(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('suspension_date', sa.Date(), nullable=True),
    sa.Column('suspension_until', sa.Date(), nullable=True),
    sa.Column('termination_date', sa.Date(), nullable=True),
    sa.Column('renewal_date', sa.Date(), nullable=True),
    sa.Column('prolongation_date', sa.Date(), nullable=True),
    sa.Column('technical_regulations', sa.Text(), nullable=True),
    sa.Column('product_group', sa.Text(), nullable=True),
    sa.Column('unified_product_list', sa.Text(), nullable=True),
    sa.Column('document_schema', sa.Text(), nullable=True),
    sa.Column('document_kind', sa.Text(), nullable=True),
    sa.Column('applicant_type', sa.String(length=100), nullable=True),
    sa.Column('applicant_role', sa.String(length=255), nullable=True),
    sa.Column('applicant_name', sa.Text(), nullable=True),
    sa.Column('applicant_address', sa.Text(), nullable=True),
    sa.Column('applicant_inn', sa.String(length=20), nullable=True),
    sa.Column('applicant_ogrn', sa.String(length=20), nullable=True),
    sa.Column('applicant_legal_form', sa.String(length=255), nullable=True),
    sa.Column('applicant_branch', sa.Text(), nullable=True),
    sa.Column('manufacturer_type', sa.String(length=100), nullable=True),
    sa.Column('manufacturer_name', sa.Text(), nullable=True),
    sa.Column('manufacturer_address', sa.Text(), nullable=True),
    sa.Column('manufacturer_inn', sa.String(length=20), nullable=True),
    sa.Column('manufacturer_ogrn', sa.String(length=20), nullable=True),
    sa.Column('manufacturer_legal_form', sa.String(length=255), nullable=True),
    sa.Column('manufacturer_branch', sa.Text(), nullable=True),
    sa.Column('certification_body', sa.Text(), nullable=True),
    sa.Column('product_origin', sa.Text(), nullable=True),
    sa.Column('product_full_name', sa.Text(), nullable=True),
    sa.Column('product_batch_size', sa.String(length=255), nullable=True),
    sa.Column('product_designation', sa.Text(), nullable=True),
    sa.Column('product_type', sa.String(length=255), nullable=True),
    sa.Column('product_brand', sa.String(length=255), nullable=True),
    sa.Column('product_model', sa.String(length=255), nullable=True),
    sa.Column('product_article', sa.String(length=255), nullable=True),
    sa.Column('product_grade', sa.String(length=255), nullable=True),
    sa.Column('product_codes', sa.Text(), nullable=True),
    sa.Column('product_gtin', sa.String(length=255), nullable=True),
    sa.Column('product_serial_number', sa.String(length=255), nullable=True),
    sa.Column('product_standards', sa.Text(), nullable=True),
    sa.Column('test_laboratory', sa.Text(), nullable=True),
    sa.Column('test_protocol_date', sa.Date(), nullable=True),
    sa.Column('test_protocol_number', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('search_text', sa.Text(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registry_documents_id'), 'registry_documents', ['id'], unique=False)
    op.create_index(op.f('ix_registry_documents_import_batch_id'), 'registry_documents', ['import_batch_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_registry_documents_import_batch_id'), table_name='registry_documents')
    op.drop_index(op.f('ix_registry_documents_id'), table_name='registry_documents')
    op.drop_table('registry_documents')
    op.drop_index(op.f('ix_import_batches_id'), table_name='import_batches')
    op.drop_table('import_batches')
    # ### end Alembic commands ###
